### ISSUE TITLE
Many experiments lack stack attach nodes

### ISSUE THREAD

**Issue by CobaltWolf** [raveloda/Coatl-Aerospace#10]
Some of the larger ones, such as the orbital telescope, would benefit from having stack attach nodes so they can be properly stacked.

**Comment by raveloda** [comment]
Anything that made sense to have one should have it, but I think I coded them wrong. I will follow up

**Comment by CobaltWolf** [comment]
I'll (see if I can remember) try to take a look at them later today. 

-----Original Message-----

**Comment by raveloda** [comment]
I fixed the Telescope and will continue to check others that should have them to make sure that they do

**Comment by raveloda** [comment]
Were there any other experiments you think need an attachment node?

**Comment by raveloda** [comment]
Let me know if you find more that need it. I couldn't think of any others
