### ISSUE TITLE
Test RemoteTech antenna Configs

### ISSUE THREAD

**Issue by raveloda** [raveloda/Coatl-Aerospace#16]
See #5 
General Balancing pass on the antenna stats based on stock and RT configs. This should include consideration for the new antenna beings added.
- [x] Test komodo's configs (screwed up by Github formatting)

**Comment by raveloda** [comment]
> //CA-A100 Small Dish Antenna
> @PART[dish_S]:AFTER[CoatlAerospace]:NEEDS[RemoteTech]
> {
>   @cost = 1000
>   // a bit more money.
>   !MODULE[ModuleDataTransmitter] {}
>   @MODULE[ModuleAnimateGeneric]
>   {
>       %allowManualControl = false
>   }
> 
>   %MODULE[ModuleRTAntenna] {
>       %Mode0DishRange = 0
>       %Mode1DishRange = 35000000000
>       // should be good to duna, but only just. Needs testing.
>       %EnergyCost = 0.60
>       // more energy hungry, but we can use solar in the inner system.
>       %DishAngle = 3
>       // mega-nerf from 55 deg.
> 
> ```
>   %DeployFxModules = 0
> 
>   %TRANSMITTER {
>       %PacketInterval = 0.3
>       %PacketSize = 2
>       %PacketResourceCost = 15.0
>   }
> ```
> 
>   }
> 
>   %MODULE[ModuleSPUPassive] {}
> }
> //CA-A300 Medium Dish Antenna
> @PART[dish_M]:AFTER[CoatlAerospace]:NEEDS[RemoteTech]
> {
>   @cost = 2000
>   // more monies.
>   !MODULE[ModuleDataTransmitter] {}
>   @MODULE[ModuleAnimateGeneric]
>   {
>       %allowManualControl = false
>   }
> 
>   %MODULE[ModuleRTAntenna] {
>       %Mode0DishRange = 0
>       %Mode1DishRange = 70000000000
>       // good to dres always, and jool on closer approaches.
>       %EnergyCost = 0.29
>       // should fit ok in a 0.4 ec/s budget, but worse than higher tech below.
>       %DishAngle = 1
>       // nerved slightly from 1.5 deg
> 
> ```
>   %DeployFxModules = 0
> 
>   %TRANSMITTER {
>       %PacketInterval = 0.3
>       %PacketSize = 2
>       %PacketResourceCost = 15.0
>   }
> ```
> 
>   }
> 
>   %MODULE[ModuleSPUPassive] {}
> }
> 
> //CA-A300 Large Dish Antenna
> @PART[dish_L]:AFTER[CoatlAerospace]:NEEDS[RemoteTech]
> {
>   @cost = 8000
>   // age old balance technique: make the awesome thing expensive.
>   !MODULE[ModuleDataTransmitter] {}
>   @MODULE[ModuleAnimateGeneric]
>   {
>       %allowManualControl = false
>   }
> 
>   %MODULE[ModuleRTAntenna] {
>       %Mode0DishRange = 0
>       %Mode1DishRange = 125000000000
>       // should be good out to jool for sure. Unsure what the min range for eeloo is.
>       %EnergyCost = 0.21
>       // low enough to run on the 0.39 ec/s rtg, better than above.
>       %DishAngle = 0.3
>       // kept at 0.3, should be a decent trade off.
> 
> ```
>   %DeployFxModules = 0
> 
>   %TRANSMITTER {
>       %PacketInterval = 0.3
>       %PacketSize = 2
>       %PacketResourceCost = 15.0
>   }
> ```
> 
>   }
> 
>   %MODULE[ModuleSPUPassive] {}
> }
> //CA-A10 Small Folding Dish Antenna
> @PART[dish_deploy_S]:AFTER[CoatlAerospace]:NEEDS[RemoteTech]
> {
>   !MODULE[ModuleDataTransmitter] {}
>   @MODULE[ModuleAnimateGeneric]
>   {
>       %allowManualControl = false
>   }
> 
>   %MODULE[ModuleRTAntenna] {
>       %Mode0DishRange = 0
>       %Mode1DishRange = 90000000
>       // I don’t know what to do with this one; unsure what the application is intended to be.
>       %EnergyCost = 0.50
>       %DishAngle = 20.0
> 
> ```
>   %DeployFxModules = 0
> 
>   %TRANSMITTER {
>       %PacketInterval = 0.3
>       %PacketSize = 2
>       %PacketResourceCost = 15.0
>   }
> ```
> 
>   }
> 
>   %MODULE[ModuleSPUPassive] {}
> }

**Comment by jmrd98** [comment]
cross-ref-ing PR #24
