### ISSUE TITLE
CA-R3900 RTG node for the magnetometer is oriented straight up, instead of an angle

### ISSUE THREAD

**Issue by raveloda** [raveloda/Coatl-Aerospace#3]

**Comment by CobaltWolf** [comment]
[You can use InsaneDruid's method for adding nodes via unity gameobjects.](http://forum.kerbalspaceprogram.com/index.php?/topic/73686-11-tantares-stockalike-soyuz-and-mir-3423042016fuji/&page=428#comment-2422748)

**Comment by raveloda** [comment]
Fixed thanks to proper configs by komodo!
