### ISSUE TITLE
Texture paths referencing swis_mesh.dds and foil2_N not found

### ISSUE THREAD

**Issue by puetzk** [raveloda/Coatl-Aerospace#35]
Looks like some texture paths need to be adjusted...

```
[ERR 08:38:42.569] Texture 'Coatl Aerospace/ProbesPlus/Assets/Antenna/swis_mesh' not found!
...
[LOG 08:39:32.271] PartLoader: Compiling Part 'Coatl Aerospace/ProbesPlus/Parts/Antenna/dish_deploy_S2/dish_deploy_S2'
[ERR 08:39:32.272] PartCompiler: Cannot replace texture as cannot find texture 'swis_mesh' to replace
[ERR 08:39:32.275] PartLoader: Encountered exception during compilation. System.NullReferenceException: Object reference not set to an instance of an object
  at PartLoader.ReplaceTextures (UnityEngine.GameObject model, System.Collections.Generic.List`1 textureNames, System.Collections.Generic.List`1 newTextures) [0x00000] in <filename unknown>:0 
  at PartLoader.CompileModel (.UrlConfig cfg, .ConfigNode partCfg, Single scaleFactor, .AvailablePart partInfo) [0x00000] in <filename unknown>:0 
  at PartLoader.ParsePart (.UrlConfig urlConfig, .ConfigNode node) [0x00000] in <filename unknown>:0 
  at PartLoader+<CompileParts>c__Iterator62.MoveNext () [0x00000] in <filename unknown>:0 
[ERR 08:39:32.278] PartCompiler: Cannot compile part
```

it looks like swis_mesh.dds is needed by Assets\ca_SWIS.mu and also Assets\Antenna\dish_deploy_S2.mu, but the file is only in the upper folder.

Also 

```
[LOG 08:46:25.994] Load(Model): Coatl Aerospace/ProbesPlus/Assets/ca_ESM
[ERR 08:46:26.000] Texture 'Coatl Aerospace/ProbesPlus/Assets/foil2_N' not found!
```

This one was probably supposed to be mat_foil2_N?

**Comment by raveloda** [comment]
I fixed the first issue, but could not find any references to foil2_N in the ESM config as noted on the second issue. I'm going to close this but I can open a new issue report for the separate ESM reference.

**Comment by puetzk** [comment]
It's in the ca_ESM.mu file (the model, as the error message said), not the .cfg

**Comment by raveloda** [comment]
I don't know why it triggers the error. The textures display correctly. I think it's because Firespitter is taking over texture loading for that part.

**Comment by puetzk** [comment]
Dunno then. I didn't see any obvious rendering problem, just saw the messages in the log (while reading through it to troubleshoot a different problem).

**Comment by raveloda** [comment]
I will keep a lookout. Might need to re-export the mu from Unity
