### ISSUE TITLE
Lahar thrust vector possibly offset

### ISSUE THREAD

**Issue by CobaltWolf** [raveloda/Coatl-Aerospace#38]
http://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-v0142-beta-102316/&page=44#comment-2850334

**Comment by raveloda** [comment]
Lahar model was updated with a new nozzle and group, removing any offset angles. Thrust vector confirmed to be along center axis
