### ISSUE TITLE
Add Cassini-inspired parts (and Huygens)

### ISSUE THREAD

**Issue by raveloda** [raveloda/Coatl-Aerospace#41]
Models
Textures
In-game
Balancing

**Comment by raveloda** [comment]
Parts will include
- Cassini Probe core
- Fuel Tank
- Radial MP Fuel tank (sm. sphere)
- Radial MP Fuel tank (long)
- Size Adapter Fuel Tank
- Engine
- Antenna Dish
- Magnetometer
- Imaging platform
- RCS Attitude and Maneuver thrusters
- Lander Radial Decoupler
- Lander heatshield
- Lander Probe Core
- Lander Parachute
- RTG? Remake of the current 8200?
- New reaction wheel? Cassini's RWs are cool
- New size of Thermal louver? Will have to see how the current ones fit
- And more as needed

**Comment by raveloda** [comment]
2.5m dia. HGA, 1.5m dia. octagonal probe core (go up to a decagon?). 0.9375m dia. Main tank. Roughly 3.2145m tall without the engine.

**Comment by CobaltWolf** [comment]
nerrrrrrrrd

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017

**Comment by raveloda** [comment]
Shoo

**Comment by CobaltWolf** [comment]
fite me

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017

**Comment by raveloda** [comment]
Parts pushed back to BETA 16

**Comment by raveloda** [comment]
Parts being worked on
