### ISSUE TITLE
Inconsistent PhysicalSignificance settings for Landvermesser parts

### ISSUE THREAD

**Issue by danielspicar** [raveloda/Coatl-Aerospace#44]
Hi

Thanks for the mod. 

I tried to build a Landvermesser probe and noticed that the soil scoop (ca_landv_soilScoop) and the survey camera (ca_landv_cam_s1) didn't have PhysicsSignificance = 1 while the other parts of this probe seem to have it. Makes it hard to balance the craft.

**Comment by raveloda** [comment]
Settings changed to reflect. I'll keep an eye out for other parts missing this
