### ISSUE TITLE
Dish antennas too heavy

### ISSUE THREAD

**Issue by jsolson** [raveloda/Coatl-Aerospace#5]
The A100, A200 and A300 antennas seem to me about 10x heavier than they should be. 40, 60 and 75 kg (or less!) would be more reasonable for these. The squad DTS-M1 is 30 kg.

**Comment by raveloda** [comment]
I can reduce the A100, maybe the A300, but the larger antenna are heavier on purpose. These are high-gain antenna unlocked earlier in the tech tree, I don't want them to be too overpowered so early on. The idea is that lighter building materials are developed later on the tech levels. It's a trade off of early efficiency vs. weight.
To summarize, it's a gameplay balance decision, not a realism decision

**Comment by jsolson** [comment]
I went and checked the remote tech dishes since those resemble yours and they run a half ton to a ton. So on second thought, leave them be, you're in the right neighborhood compared to a fairly heavily used antenna mod. I can MM patch what I don't like easy enough.

**Comment by raveloda** [comment]
Okay. I think the weight on the A100 will come down a bit anyway. This is great feedback! Thank you very much.

**Comment by raveloda** [comment]
Closing this issue to combine with feedback provided by komodo
