### ISSUE TITLE
lahar model produces torqe when stack attached

### ISSUE THREAD

**Issue by gabevenberg** [raveloda/Coatl-Aerospace#51]
the problem follows the model, even when transplanting it to a different engine .cfg.

**Comment by raveloda** [comment]
This is the same as issue #38 which has fixed the problem for others. I' unable to replicate this. I am looking for anyone to help test this

**Comment by gabevenberg** [comment]
Linux, BTW, if that makes a difference. (didn't think it would, but you never know...) are you sure that the old model hasn't slipped into the dev branch so far? (dont mean to sound patronizing, just wracking my brain trying to think of what it might be.) is there a way i could check the model on my end?

**Comment by gabevenberg** [comment]
intresting descovery: if i give the engine some fuel (so that KER will recognize it without having to attach a fueltank) it still has the torqe, and in the same amount. as nither of the nodes are being used, (1 part craft) it would seem to rule out node issues. how is the COG defined for a part model?

**Comment by gabevenberg** [comment]
was my own stupidity... sorry.
