### ISSUE TITLE
Texture load errors in log

### ISSUE THREAD

**Issue by jsolson** [raveloda/Coatl-Aerospace#54]
A few files appear to be invalid/corrupt.
```
\GameData\Coatl Aerospace\ProbesPlus\Assets\mat_cf_N.dds
\GameData\Coatl Aerospace\ProbesPlus\Assets\mat_foilEdge_N.dds
\GameData\Coatl Aerospace\ProbesPlus\Assets\mat_foil_N.dds
\GameData\Coatl Aerospace\ProbesPlus\Assets\mat_stock_N.dds
```

**Comment by raveloda** [comment]
All the normal maps huh? I will investigate

**Comment by Gordon-Dry** [comment]
As mentioned here
http://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-v015-beta-41417/&do=findComment&comment=3124836
it seems to be broken when it's not DXT5 but ATI2

**Comment by raveloda** [comment]
Fixed with DDS texture re-encoding to DTX5_NM. Thanks!
