### ISSUE TITLE
[Bug] Jib engine config is missing a bracket

### ISSUE THREAD

**Issue by PhineasFreak** [raveloda/Coatl-Aerospace#56]
At: https://github.com/raveloda/Coatl-Aerospace/blob/809a60d3dffef2778d862b05dd2df5d084e74182/GameData/Coatl%20Aerospace/ProbesPlus/Parts/Propulsion/ca_engine_jib.cfg#L162

It also breaks any part modules that follow the ModuleEngines when using Module Manager to patch them.

**Comment by raveloda** [comment]
It was bound to happen eventually. Good catch! Thank you
