### ISSUE TITLE
RemoteTech, omni antennas not working for some reason

### ISSUE THREAD

**Issue by Jimbodiah** [raveloda/Coatl-Aerospace#58]
The omnidirectional antennas are not working for some reason when using the Remote Tech patch. 

I checked the coatls RT patch but can't see why it wouldn't work.

**Comment by raveloda** [comment]
@AkiraR has updated RT configs, anyone else still having issues with omni antenna?

**Comment by raveloda** [comment]
Not had any new reports. Closing. Will see if anyone reports issues in Beta 16
