### ISSUE TITLE
CA-SB15 Landvermesser Solid Rocket Retromotor SRM Jettison staging issue

### ISSUE THREAD

**Issue by Gordon-Dry** [raveloda/Coatl-Aerospace#66]
I can toggle between "SRM Jettison: Staged" and "SRM Jettison: Not Staged", but the staging doesn't add/remove anything.

That's a problem for a proper dV readout.

**Comment by Gordon-Dry** [comment]
I just got a clue.

A part that got ModuleEngines* cannot also have a ModuleDecoupler.

That is simply a no-go.

The decoupler has to be at a part without further staging-related modules.

Actually I'm trying to move the ModuleDecoupler from ca_landv_srm to ca_landv_core.

**Comment by Gordon-Dry** [comment]
Quick test of my changes.

Minimum KSP environment:
```
GameData\Coatl Aerospace\
GameData\CommunityResourcePack\
GameData\DMagicScienceAnimate\
GameData\InterstellarFuelSwitch\
GameData\PatchManager\
GameData\Squad\
GameData\SquadExpansion\
GameData\ModuleManager.4.1.2.dll
```
New sandbox game.
Enabled all SAS upgrades for sandbox game.

Loaded the provided craft file into VAB, staging already looking good.
Clicked launch button.
On launchpad, cheated to orbit (default SMA 686750).


The shroud of the engine's built in decoupler (jettisonName = fairTop) is invisible now - because the decoupler went to the main lander core.
This means this shroud mesh also needs to move to the lander core.

**Comment by Gordon-Dry** [comment]
I don't know how to find out how the bottom attach node is named.
`explosiveNodeID = bottom`
seems not to work because I got log spamming
`Cannot find fx group of that name for decoupler`
now.

**Comment by Gordon-Dry** [comment]
But at least I see the retro engine in MechJeb and KER staging now ...

The "Cannot find fx group of that name for decoupler" issue makes the game really lag...
Now I even consider in having a seperate decoupler part to be used ...

Damnit, is this a difficult-to-fix thing.

**Comment by raveloda** [comment]
> But at least I see the retro engine in MechJeb and KER staging now ...
> 
> The "Cannot find fx group of that name for decoupler" issue makes the game really lag...
> Now I even consider in having a seperate decoupler part to be used ...
> 
> Damnit, is this a difficult-to-fix thing.

Okay, I will look at options for having a separate decoupler. Surveyor Engine needs some love anyway

**Comment by raveloda** [comment]
Surveyor parts will be re-worked on a future redesign. Lots of things to fix that aren't worth doing one at a time
