### ISSUE TITLE
CA-MV04 got no plume

### ISSUE THREAD

**Issue by Gordon-Dry** [raveloda/Coatl-Aerospace#67]
This config doesn't seem to work:
inside GameData\Coatl Aerospace\ProbesPlus\Compatibility\RealPlume.cfg

```
@PART[ca_jib]:NEEDS[RealPlume,SmokeScreen]
{
	@MODULE[ModuleEngines*]
	{
		@name = ModuleEnginesFX
		%powerEffectName = Hypergolic-OMS-White
	}
    PLUME
    {
        name = Hypergolic-OMS-White
        transformName = Thrust_transform
        localRotation = 0,0,0
        localPosition = 0,0,0
        plumePosition = 0,0,0.05
        flarePosition = 0,0,-0.72
        fixedScale = 0.1
        energy = 1
        speed = 1
    }
} 
```

**Comment by raveloda** [comment]
Is the issue that no plume shows up? Or that the plume is wrong? I was able to get a plume to show

This is the plume that shows for me:

[https://imgur.com/3bkFY0D.png](https://imgur.com/3bkFY0D)

**Comment by Gordon-Dry** [comment]
I have to recheck - there was another engine (BDB) that works on MonoPropellant with no plume and if I'm right it's working again...

**Comment by raveloda** [comment]
@Gordon-Dry , did you ever see this issue again?

**Comment by Gordon-Dry** [comment]
I have to recheck.

So many thing to be aware of - in a heavily modded install.

**Comment by raveloda** [comment]
@Gordon-Dry I think this is fixed. I'll close for now and re-open if you see this again. It may also be a conflict, which we can look into

**Comment by Gordon-Dry** [comment]
I guess I know what's going on.
The cloned part of the ca_jib aka. CA-MV04 "Jib" MonoPropellant Engine got no plume.
Because it is cloned after the RealPlume patch as it seems.

No wait, it's not cloned, it got a dedicated config - and no RealPlume patch.

I'll add one in a minute or so...

This one:
ca_jib-mk2 aka. CA-MV04-CP "Jib" MonoPropellant Engine

**Comment by Gordon-Dry** [comment]
https://github.com/raveloda/Coatl-Aerospace/pull/75

**Comment by Gordon-Dry** [comment]
Well, the "normal" MV04 still got no plume.
