### ISSUE TITLE
Landvermesser got no attitude thrusters (Surveyor had them)

### ISSUE THREAD

**Issue by Gordon-Dry** [raveloda/Coatl-Aerospace#80]
I just checked some tech specs for the Surveyor and it's clear:
Surveyor landers got Nitrogen thrusters for attitude.
Quote:
> Nitrogen gas jets provided attitude control when the engines were off. 

These attitude control jets have been near the foot pads at the landing legs.
See page 2 of https://www.hq.nasa.gov/alsj/NASA-SP-184.pdf

As stock KSP is not capable of using the 3 vernier engines for attitude control (as the mod ThrottleControlledAvionics would provide) these Nitrogen attitude thrusters should be added to the ca_landv_core as built-in stock MonoPropellant RCS thrusters.

I'm not sure if KSP is capable of having RCS thrusters at animated landing legs without specialized additional mods, so as an alternative they need to be emedded in the main lander core.

It's too much of a fiddle to find tiny-enough RCS parts that even have to be attached to the lander with the use of the move and rotate gizmos in VAB - so these thrusters need to be built-in for convenience. The mesh and the triangle footprint shape make attached parts float in weird angles.
(And as it's even impossible to add RCS parts at the animated landing legs without specialized additional mods, this should be no option at all).

**Comment by Gordon-Dry** [comment]
Why is this an issue?

With MandatoryRCS (or old RWSaturatable or a patch that makes the reaction wheels have 5% of their original torque) the ca_landv_core can not be oriented quickly enough by MechJeb autoland so it just crashes.

(The stock reaction wheels are just too unrealistically powerful)

**Comment by Gordon-Dry** [comment]
Cross reference:
https://github.com/raveloda/Coatl-Aerospace/issues/66

And (now just hypothetical):
As soon as "stageable RCS" is added to KSP this added RCS staging to the ca_landv_core would PERHAPS trigger a new problem with the just-solved decoupling issue of the ca_landv_srm - because the decoupler for the retro srm is moved from the engine (where it just does not belong) to the lander.

**Comment by raveloda** [comment]
RCS will be added to any re-design or re-make of Surveyor. Currently, it would be a lot of work that would be better off just re-doing the craft
