### ISSUE TITLE
No fuel in fuel tanks 

### ISSUE THREAD

**Issue by alkopop79** [raveloda/Coatl-Aerospace#84]
There is absolutely no fuel in any of the fuel tanks on Mac OS X 10.3.6 and KSP 1.7.3. Right-clicking the parts shows no options just the default ones (same vessel interaction, autostrut disabled, rigid attachment).

**Comment by raveloda** [comment]
This sounds to me like a possible mod conflict. Can you post your KSP.log? Are you running real fuels or any similar mods?

**Comment by raveloda** [comment]
If you have this issue and can post a log, let me know, or in the Forums
