### ISSUE TITLE
Is this Mod Dead?

### ISSUE THREAD

**Issue by Joey-Destroyah** [raveloda/Coatl-Aerospace#87]
Or are you working on an extremely time consuming project for this or another mod?

**Comment by Kash-420** [comment]
He's still working on it, he posts on the forums about the upcoming parts. If you want to use the mod with 1.10.1 there's one part that you need to delete and it will work fine until the next update.

**Comment by raveloda** [comment]
I am going to close this tkt. Feel free to join the mod discussion at [https://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-beta-3172020-18-19/](url)
