### ISSUE TITLE
Barquetta Texture Bug

### ISSUE THREAD

**Issue by Kash-420** [raveloda/Coatl-Aerospace#88]
There is a small gap in the texture on the barquetta probe that lets you see through it in the VAB and in flight. I've attached a picture showing what I mean.

![Barqetta](https://user-images.githubusercontent.com/70769646/92263600-e01bf100-eeaa-11ea-8130-f3fd86963fd5.png)

Thank you for the awesome mod!

**Comment by raveloda** [comment]
Barquetta is getting an entirely new model on the next update. [See preview here](https://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-beta-3172020-18-19/&do=findComment&comment=3781735) Thank you for reporting it though!
