### ISSUE TITLE
KSP loading stuck at coatl

### ISSUE THREAD

**Issue by parpar78** [raveloda/Coatl-Aerospace#90]
Hi,

When i load KSP it gets stuck at one of the Coatl files as shown in screenshot. Maybe you know why?
Problem started after updating the mod.

Thanks,

Patrick

![image](https://user-images.githubusercontent.com/55486389/97028603-a5564100-155c-11eb-82bf-ca399051f56e.png)

**Comment by raveloda** [comment]
DragCube issue on Solar Panel. Should be fixed on the latest Repository (Download the "code" version of the mod from the github main page)
