### ISSUE TITLE
Is this mod dead?

### ISSUE THREAD

**Issue by Joey-Destroyah** [raveloda/Coatl-Aerospace#91]
Still updating it? Or is the mod in some sort of closed off beta state?

**Comment by Joey-Destroyah** [comment]
never mind. Cobaltwolf is updating anyway

**Comment by raveloda** [comment]
> never mind. Cobaltwolf is updating anyway

I am not sure what you mean, Cobalt has his own mods he works on. This mod is not dead, but updates are sporadic for the time being
